version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7.19
    environment:
      - MYSQL_DATABASE=databasetcp
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper

  kafka:
   image: wurstmeister/kafka
   container_name: kafka
   ports:
    - "9092:9092"
   environment:
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  app:
   build:
    dockerfile: ./docker/app.dockerfile
    context: .
   image: adesozasilva/app
   container_name: app
   ports:
      - "8080:8080"
   depends_on:
      - "db"
      - "kafka"
